CREATE TABLE CLIENTE (
	ID			INTEGER NOT NULL,
	TX_NOME		TEXT NOT NULL,
	ID_STATUS	INTEGER NOT NULL,
	TX_APELIDO	TEXT NOT NULL,
	TX_SENHA	TEXT NOT NULL,
	CONSTRAINT "PK_CLIENTE" PRIMARY KEY("ID")
);


CREATE TABLE TREINO (
	ID	INTEGER NOT NULL,
	TX_DESCRICAO	TEXT NOT NULL,
	TX_MODULO	TEXT NOT NULL,
	TX_TIPO	TEXT NOT NULL,
	TX_LOCALIZADO	TEXT NOT NULL,
	NR_DURACAO	INTEGER NOT NULL,
	NR_REPETICAO	INTEGER NOT NULL,
	NR_ORDEM	INTEGER NOT NULL,
	CONSTRAINT "PK_TREINO" PRIMARY KEY("ID")
);

CREATE TABLE PROGRAMACAO (
	ID	INTEGER NOT NULL,
	ID_CLIENTE	INTEGER NOT NULL,
	ID_TREINO	INTEGER NOT NULL,
	DT_INICIO	INTEGER NOT NULL,
	DT_FINAL	INTEGER NOT NULL,
	CONSTRAINT "PK_PROGRAMACAO" PRIMARY KEY("ID"),
	CONSTRAINT "AK_PROGRAMACAO" UNIQUE("ID_CLIENTE","ID_TREINO","DT_INICIO","DT_FINAL"),
	CONSTRAINT "PROG_CLIENTES" FOREIGN KEY("ID_CLIENTE") REFERENCES "CLIENTE"("ID"),
	CONSTRAINT "PROG_TREINOS" FOREIGN KEY("ID_TREINO") REFERENCES "TREINO"("ID")
);


CREATE TABLE EXECUCAO (
	ID	INTEGER NOT NULL,
	ID_CLIENTE	INTEGER NOT NULL,
	ID_TREINO	INTEGER NOT NULL,
	DT_REGISTRO	INTEGER NOT NULL,
	IN_STATUS	INTEGER NOT NULL,
	CONSTRAINT "PK_EXECUCAO" PRIMARY KEY("ID"),
	CONSTRAINT "AK_EXECUCAO" UNIQUE("ID_CLIENTE","ID_TREINO","DT_REGISTRO"),
	CONSTRAINT "EXECUCAO_CLIENTES" FOREIGN KEY("ID_CLIENTE") REFERENCES "EXECUCAO"("ID"),
	CONSTRAINT "EXECUCAO_TREINOS" FOREIGN KEY("ID_TREINO") REFERENCES "TREINO"("ID")
);

CREATE TABLE FEEDBACK (
	ID	INTEGER NOT NULL,
	ID_EXECUCAO	INTEGER NOT NULL,
	ID_CLIENTE	INTEGER NOT NULL,
	DT_REGISTRO	INTEGER NOT NULL,
	TX_DESCRICAO	TEXT NOT NULL,
	NR_NOTA	INTEGER NOT NULL,
	CONSTRAINT "PK_FEEDBACK" PRIMARY KEY("ID"),
	CONSTRAINT "AK_FEEDBACK" UNIQUE("ID_EXECUCAO","ID_CLIENTE","DT_REGISTRO"),
	CONSTRAINT "FEEDBACK_CLIENTES" FOREIGN KEY("ID_CLIENTE") REFERENCES "CLIENTE"("ID"),
	CONSTRAINT "FEEDBACK_EXECUCOES" FOREIGN KEY("ID_EXECUCAO") REFERENCES "EXECUCAO"("ID")
);

